[package]
name = "search-location"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.27"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.64", features = ["serde-serialize"] }
