/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BamPistache (https://sketchfab.com/karinkreeft8)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-0caafb7e837047a688a3e504c0ea74af
title: Earth
*/

import { useGLTF } from "drei/useGLTF";

// @ts-ignore
import modelPath from "../assets/earth/scene.glb";

export const Earth = (props: any) => {
  const gltf = useGLTF(modelPath);
  const { materials, nodes } = gltf;

  return (
    <group {...props} dispose={null} scale={[1 / 8, 1 / 8, 1 / 8]}>
      <mesh
        material={materials.blinn1}
        geometry={(nodes.earth4_blinn1_0 as any).geometry}
      />
      <mesh
        material={materials.lambert1}
        geometry={(nodes.earth4_lambert1_0 as any).geometry}
      />
    </group>
  );
};
