name: Test e2e

on:
  workflow_call:
    inputs:
      APP_URL:
        type: string
        required: true

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: ["1/1"]
        browser: [firefox, chromium]
        # browser: [firefox, chromium, webkit]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ matrix.browser }}

      - run: bunx playwright install ${{ matrix.browser }} --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        working-directory: packages/e2e

      - run: |
          bunx playwright test \
            --project ${{ matrix.browser }} \
            --shard ${{ matrix.shard }} \
            --reporter github \
            --forbid-only \
            --workers 1
        working-directory: packages/e2e
        env:
          APP_URL: ${{ inputs.APP_URL }}

      - uses: actions/upload-artifact@v3
        with:
          name: playwright-screenshots-${{ matrix.browser }}
          path: packages/e2e/playwright-screenshots
