name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - uses: bahmutov/npm-install@v1.7.8

      - run: yarn type
      - run: yarn lint
      - run: yarn test
      - run: yarn generateLocations
      - run: yarn build
      - run: yarn surge ./build staging-timezone-rocks.surge.sh
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
