name: main

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.ref_type != 'tag'
    outputs:
      published_url: ${{ steps.publish.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install --frozen-lockfile

      - run: bunx vite build
        working-directory: packages/app-builder

      - name: Publish
        id: publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: timezone-rocks
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: disclaim preview url in commit comment
        uses: peter-evans/commit-comment@v3
        with:
          body: |
            [preview](${{ steps.publish.outputs.url }})

      - run: bun type
      - run: bun lint
      - run: npm run test

  e2e:
    needs: [main]
    uses: ./.github/workflows/_test-e2e.yml
    with:
      APP_URL: ${{ needs.main.outputs.published_url }}
    secrets: inherit
