name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile

      - run: yarn generateLocations
      - run: yarn build

      - name: deploy preview
        id: deploy-preview
        run: |
          previewUrl=timezone-rocks-$SHA.surge.sh
          echo ::set-output name=previewUrl::$previewUrl
          yarn surge ./dist $previewUrl

          branch=`node -e "console.log(process.env.REF.replace(/^(refs\/(heads\/)?)?/,'').replace(/\W/g,'-'))"`
          branchUrl=timezone-rocks-$branch.surge.sh
          echo ::set-output name=branchUrl::$branchUrl
          yarn surge ./dist $branchUrl
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}

      - name: disclaim preview url in commit comment
        uses: peter-evans/commit-comment@v1
        with:
          token: ${{ github.token }}
          sha: ${{ github.sha }}
          body: |
            [preview](https://${{ steps.deploy-preview.outputs.previewUrl }})

      - run: yarn type
      - run: yarn lint
      - run: yarn test
