name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          key: $cargo-cache-${{ hashFiles('crates/**/Cargo.lock') }}

      - uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm generateLocations
      - run: pnpm build-wasm:production
      - run: pnpm build

      - name: deploy preview
        id: deploy-preview
        run: |
          previewUrl=timezone-rocks-$SHA.surge.sh
          echo ::set-output name=previewUrl::$previewUrl
          pnpm surge ./dist $previewUrl

          branch=`node -e "console.log(process.env.REF.replace(/^(refs\/(heads\/)?)?/,'').replace(/\W/g,'-'))"`
          branchUrl=timezone-rocks-$branch.surge.sh
          echo ::set-output name=branchUrl::$branchUrl
          pnpm surge ./dist $branchUrl
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}

      - name: disclaim preview url in commit comment
        uses: peter-evans/commit-comment@v1
        with:
          token: ${{ github.token }}
          sha: ${{ github.sha }}
          body: |
            [preview](https://${{ steps.deploy-preview.outputs.previewUrl }})

      - run: pnpm type
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm test:wasm
