name: main

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build:app

      - name: Publish
        id: publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PUBLISH_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: disclaim preview url in commit comment
        uses: peter-evans/commit-comment@v2
        with:
          token: ${{ github.token }}
          sha: ${{ github.sha }}
          body: |
            [preview](${{ steps.publish.outputs.url }})

      - run: pnpm type
      - run: pnpm lint
      - run: pnpm test
