name: Publish to cloudflare live domain, based on the "live" tag

on:
  push:
    tags:
      - "live"

jobs:
  publish-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm build:app

      - name: Publish Main
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PUBLISH_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: timezone-rocks
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
