name: Publish to cloudflare live domain, based on the "live" tag

on:
  push:
    tags:
      - "live"

jobs:
  publish-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: bun install --frozen-lockfile

      - run: bun build:app

      - name: rewrite robot.txt
        run: |
          echo -e "User-agent: *\nAllow: /" > dist/robots.txt

      - run: bunx wrangler pages deploy dist --project-name=timezone-rocks --branch=main
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PUBLISH_TOKEN }}

  e2e:
    needs: [publish-production]
    uses: ./.github/workflows/_test-e2e.yml
    with:
      APP_URL: "https://timezone.rocks"
