name: Publish to cloudflare live domain, based on the "live" tag

on:
  push:
    tags:
      - "live"

jobs:
  publish-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: bun install --frozen-lockfile

      - run: bun build:app

      - name: Publish Main
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PUBLISH_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: timezone-rocks
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
